
#ifndef ACTIONTYPE_H
#define ACTIONTYPE_H



enum class ActionType {
    MOVE_FORWARD,
    MOVE_BACKWARD,
    ROTATE_EIGHTH_LEFT,
    ROTATE_EIGHTH_RIGHT,
    ROTATE_QUARTER_LEFT,
    ROTATE_QUARTER_RIGHT,
    SHOOT,
    INVALID_ACTION,
    SHELL_MOVE_LEFT,
    SHELL_MOVE_RIGHT,
    SHELL_MOVE_UP,
    SHELL_MOVE_DOWN,
    SHELL_MOVE_UP_LEFT,
    SHELL_MOVE_UP_RIGHT,
    SHELL_MOVE_DOWN_LEFT,
    SHELL_MOVE_DOWN_RIGHT,
};



#endif //ACTIONTYPE_H
